#!/bin/sh
cd "$(dirname "$0")/.."

local file="$(find . -name "vscode-ocelots-theme-*.vsix" | head -n 1)"
if [ -e "$file" ]; then
	code --uninstall-extension "johnryanmal.vscode-ocelots-theme"
	code --install-extension "$file"
fi